url=https://www.onliner.by
selenium_url=http://localhost:4444/wd/hub
browser_language=ru
locale=ru_RU

capabilities.browserName=chrome
capabilities.platformName=ANY
capabilities.acceptInsecureCerts=true

core_log_level=INFO
explicit_timeout=20
retry_interval=500
page_opening_strategy=BY_URL
element_loading_strategy=BY_VISIBILITY
auto_screenshot=true